import { notFound } from "next/navigation";
import { DeleteOperationsButton, OperationsForm } from "@/components/admin/operations-admin";
import { Container } from "@/components/layout/container";
import { Button } from "@/components/ui/button";
import { Link } from "@/lib/navigation";
import { operationsService } from "@/services/operations.service";
type Entity = "project" | "it-service" | "announcement";
const names = { project: ["پروژه‌های در حال اجرا", "projects"], "it-service": ["وضعیت خدمات IT", "it-services"], announcement: ["اطلاعیه‌ها", "announcements"] } as const;
export async function OperationsListPage({ entity }: { entity: Entity }) { const [title, route] = names[entity]; const rows = entity === "project" ? await operationsService.projects(true) : entity === "it-service" ? await operationsService.itServices(true) : await operationsService.announcements(true); return <main className="py-10"><Container className="max-w-6xl"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black">{title}</h1>{entity === "project" ? <p className="mt-2 text-sm text-muted-foreground">پیشرفت پروژه‌های عمومی را مدیریت کنید؛ پروژه‌های تکمیل‌شده را برای نمونه‌کارها آماده کنید.</p> : null}</div><Button asChild><Link href={`/admin/${route}/new`}>افزودن</Link></Button></div><div className="mt-8 overflow-x-auto rounded-xl border"><table className="w-full text-right text-sm"><thead className="bg-muted"><tr><th className="p-4">عنوان</th><th className="p-4">وضعیت</th>{entity === "project" ? <th className="p-4">پیشرفت</th> : null}<th className="p-4">نمایش عمومی</th><th className="p-4" /></tr></thead><tbody>{rows.map(row => <tr className="border-t" key={row.id}><td className="p-4 font-bold">{"title" in row ? row.title : "name" in row ? row.name : ""}</td><td className="p-4">{"status" in row ? row.status : "health" in row ? row.health : "severity" in row ? row.severity : ""}</td>{entity === "project" && "progress" in row ? <td className="p-4">{row.progress}٪</td> : null}<td className="p-4">{row.published ? "بله" : "خیر"}</td><td className="flex gap-2 p-4"><Button asChild size="sm" variant="outline"><Link href={`/admin/${route}/${row.id}/edit`}>ویرایش</Link></Button><DeleteOperationsButton entity={entity} id={row.id} /></td></tr>)}</tbody></table></div></Container></main>; }
export async function OperationsEditorPage({ entity, id }: { entity: Entity; id?: string }) { const row = id ? entity === "project" ? await operationsService.project(id) : entity === "it-service" ? await operationsService.itService(id) : await operationsService.announcement(id) : null; if (id && !row) notFound(); return <main className="py-10"><Container className="max-w-3xl"><h1 className="text-3xl font-black">{row ? "ویرایش" : "افزودن"} {names[entity][0]}</h1><div className="mt-8 rounded-2xl border bg-card p-6"><OperationsForm entity={entity} record={row ?? undefined} /></div></Container></main>; }
