import { z } from "zod";
import { announcementSeverities, projectStatuses, serviceHealths, ticketCategories, ticketPriorities, ticketStatuses } from "@/core/operations";

const optionalDate = z.string().trim().transform(value => value ? new Date(value) : null).refine(value => !value || !Number.isNaN(value.getTime()), "date");
export const projectSchema = z.object({ id: z.string().optional(), title: z.string().trim().min(2).max(200), description: z.string().trim().min(2).max(2000), progress: z.coerce.number().int().min(0).max(100), status: z.enum(projectStatuses), startDate: optionalDate, expectedEndDate: optionalDate, completedAt: optionalDate, published: z.boolean(), isActive: z.boolean(), sortOrder: z.coerce.number().int().min(0).max(10000) }).superRefine((value, ctx) => { if (value.status === "COMPLETED" && (value.progress !== 100 || !value.completedAt)) ctx.addIssue({ code: "custom", message: "completedProject", path: ["completedAt"] }); });
export const itServiceSchema = z.object({ id: z.string().optional(), name: z.string().trim().min(2).max(160), description: z.string().trim().max(1000), health: z.enum(serviceHealths), published: z.boolean(), isActive: z.boolean(), sortOrder: z.coerce.number().int().min(0).max(10000) });
export const announcementSchema = z.object({ id: z.string().optional(), title: z.string().trim().min(2).max(200), body: z.string().trim().min(2).max(5000), severity: z.enum(announcementSeverities), publishAt: optionalDate, expiresAt: optionalDate, pinned: z.boolean(), published: z.boolean(), isActive: z.boolean() }).superRefine((value, ctx) => { if (!value.publishAt) ctx.addIssue({ code: "custom", message: "date", path: ["publishAt"] }); if (value.publishAt && value.expiresAt && value.expiresAt <= value.publishAt) ctx.addIssue({ code: "custom", message: "date", path: ["expiresAt"] }); });
export const ticketInputSchema = z.object({ requesterName: z.string().trim().min(2).max(100), email: z.string().trim().email().max(254), phone: z.string().trim().max(30), category: z.enum(ticketCategories), title: z.string().trim().min(3).max(200), description: z.string().trim().min(10).max(5000), priority: z.enum(ticketPriorities), honeypot: z.string().max(200) });
export const ticketLookupSchema = z.object({ trackingCode: z.string().trim().regex(/^TKT-[A-Z0-9]{12}$/), email: z.string().trim().email().max(254) });
export const ticketUpdateSchema = z.object({ id: z.string().min(1), status: z.enum(ticketStatuses), internalNotes: z.string().trim().max(10000) });
export type ProjectInput = z.output<typeof projectSchema>; export type ItServiceInput = z.output<typeof itServiceSchema>; export type AnnouncementInput = z.output<typeof announcementSchema>;
