"use client";
import { useState } from "react";
import { submitTicketAction } from "@/actions/ticket.actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
const categories = [["SOFTWARE", "مشکل نرم‌افزاری"], ["HARDWARE", "مشکل سخت‌افزاری"], ["ACCESS", "درخواست دسترسی"], ["SOFTWARE_REQUEST", "درخواست نرم‌افزار"], ["NETWORK", "مشکل شبکه"], ["ACCOUNT", "درخواست حساب کاربری"], ["OTHER", "سایر"]] as const;
export function TicketForm() { const [state, setState] = useState<{ code?: string; error?: string }>({}); return state.code ? <div className="rounded-2xl border border-success/30 bg-success/10 p-8 text-center"><h2 className="text-xl font-bold">تیکت شما ثبت شد</h2><p className="mt-3">کد پیگیری شما: <b dir="ltr">{state.code}</b></p><p className="mt-2 text-sm text-muted-foreground">این کد و ایمیل ثبت‌شده را برای پیگیری نگه دارید.</p></div> : <form className="grid gap-5" action={async form => { const result = await submitTicketAction(form); setState(result.success ? { code: result.trackingCode } : { error: result.code === "RATE_LIMIT" ? "تعداد تلاش‌ها زیاد است؛ کمی بعد دوباره امتحان کنید." : "اطلاعات یا فایل پیوست را بررسی کنید." }); }}><div className="grid gap-5 sm:grid-cols-2"><Field label="نام و نام خانوادگی"><Input name="requesterName" required /></Field><Field label="ایمیل"><Input name="email" type="email" required dir="ltr" /></Field><Field label="شماره تماس"><Input name="phone" /></Field><Field label="نوع درخواست"><Select name="category" required><SelectTrigger><SelectValue placeholder="انتخاب کنید" /></SelectTrigger><SelectContent>{categories.map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="عنوان"><Input name="title" required /></Field><Field label="توضیحات"><Textarea className="min-h-36" name="description" required /></Field><Field label="اولویت"><Select name="priority" defaultValue="MEDIUM"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="LOW">کم</SelectItem><SelectItem value="MEDIUM">متوسط</SelectItem><SelectItem value="HIGH">بالا</SelectItem><SelectItem value="URGENT">فوری</SelectItem></SelectContent></Select></Field><Field label="فایل پیوست (حداکثر ۳ فایل، هر فایل ۱۰ مگابایت)"><Input accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx,.zip" multiple name="attachments" type="file" /></Field><input aria-hidden="true" className="hidden" name="honeypot" tabIndex={-1} /><p className="text-sm text-destructive">{state.error}</p><Button type="submit">ثبت تیکت</Button></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><Label>{label}</Label>{children}</label>; }
